services:
  juavaal2:
    restart: unless-stopped
    build: ./juavaal2
    command: gunicorn juavaal2.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./juavaal2:/usr/src/app
    ports:
      - 127.0.0.1:${PRODUCTION_DOCKER_DJANGO_API_FORWARDED_PORT}:8000
    env_file:
      - .env
      - .env.prod
    networks:
      - postgis_postgis

networks:
   postgis_postgis:
      driver: bridge
      external: true
